Updated template to conform with new event/restful flow
imoverse/dev-cli pull request #9
Opened 2020-12-02 12:46 UTC by Maritt

2020-12-02 12:46 UTC, Maritt commented on templates/service/Dockerfile
note updated node version

2020-12-02 13:07 UTC, iorg1 requested changes
Payload bør inkludere ID slik at denne ikke opprettes på serversiden. Ellers OK!

2020-12-02 13:07 UTC, iorg1 commented on templates/service/src/[resource]/db.js
> +    uuid(),
Hmmm, pga. idempotency bør id sendes med i payloaden til ressursen. Da vil ikke eksempelvis dobbelklikk medføre flere entities.

2020-12-02 14:32 UTC, kress92cs commented on templates/service/Dockerfile
Gleder meg :1st_place_medal:

2020-12-04 09:25 UTC, iorg1 approved these changes

2020-12-04 09:28 UTC, merged

2020-12-04 09:29 UTC, imove-ops commented
:tada: This PR is included in version 2.5.0 :tada:

The release is available on:
- `npm package (@latest dist-tag)`
- [GitHub release](https://github.com/imoverse/dev-cli/releases/tag/v2.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: